language: android
android:
 components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

jdk: oraclejdk7

script: ./gradlew testDebug

after_success:
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
